name: Automated Jest testing

on:
- workflow_dispatch
- pull_request

jobs: 
  run-unit-test: 
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout github actions
      uses: actions/checkout@master
    
    - name: Set up NodeJS
      uses: actions/setup-node@v1
    
    - name: Install the dependencies
      run: npm install
    
    - name: Run the unit tests
      run: npm run test-unit
